name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  echart_flutter:
    path: ../
  intl: ^0.17.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
