include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    public_member_api_docs: true
    require_trailing_commas: true
    sort_child_properties_last: true
    unawaited_futures: true
    unsafe_html: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
