name: echart_flutter
description: A library that make it easy to draw charts in Flutter.
version: 0.1.0
homepage: https://github.com/enechain/echart_flutter

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.8.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
